[phases.setup]
nixPkgs = ["python3Full", "nodejs"]

[phases.install]
cmds = [
  "cd server && python3 -m pip install -r requirements.txt",
  "cd client && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build"
]

[start]
cmd = "cd server && gunicorn config.wsgi"
